steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: teched-apj01
    integrationFlowId: S0004391153-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: teched-apj01
    integrationFlowId: S0004391153-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: teched-apj01
    integrationFlowId: S0004391153-flow4
    integrationFlowName: S0004391153-flow4
    packageId: CICD
    filePath: S0004391153-flow4.zip